version: 2.1

orbs:
  node: circleci/node@5

jobs:
  install-and-scan:
    executor: node/default
    environment:
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_PROJECT_KEY: Daud1024_Jobly
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install SonarQube Scanner
          command: npm install --save-dev sonarqube-scanner
      - run:
          name: Run SonarQube Scanner
          command: |
            npx sonarqube-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.sources=. \
              -Dsonar.exclusions=node_modules/**,test-results/**

workflows:
  install-and-scan-workflow:
    jobs:
      - install-and-scan


