version: 2.1 # Fix

orbs:
  node: circleci/node@5

jobs:
  test-node:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
      SONAR_HOST_URL: https://sonarcloud.io
      SONAR_PROJECT_KEY: Daud1024_Jobly
      SONAR_ORGANIZATION: daud1024  # Replace with your actual organization key
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Jest JUnit and SonarQube Scanner
          command: npm install jest-junit sonarqube-scanner --save-dev
      - run:
          name: Create Test Results Directory (if missing)
          command: mkdir -p ./test-results
      - run:
          name: Run SonarQube Scanner
          command: |
            npx sonarqube-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORGANIZATION \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.sources=. \
              -Dsonar.exclusions=node_modules/**,test-results/** \
              -Dsonar.tests=./test-results

workflows:
  build-and-test:
    jobs:
      - test-node

